// utils/seoMappings.js
export const slugToSeoKeyMap = {
  // Products slugs
  "bulk-sms": "bulkSMS",
  "bulk-voice": "bulkVoice",
  "whatsapp-service": "whatsappService",
  "digital-marketing": "digitalMarketing",
  "whats-chatbot": "whatsappChatbot",
  "digital-auto": "digitalAutomation",
  "design-develop": "designDevelopment",
  "graphic-design": "graphicDesign",
  "alert-system": "alertSystem",
  "ivr-system": "ivrSystem",
  "bulk-email": "bulkEmail",
  "outdoor-marketing": "outdoorMarketing",
  // Industries slugs
  hospital: "hospital",
  banking: "banking",
  insurance: "insurance",
  finance: "finance",
  "real-estate": "realEstate",
  travel: "travel",
  ecommerce: "ecommerce",
  education: "education",
  automobile: "automobile",
  entertainment: "entertainment",
  broadcasting: "broadcasting",
  fitness: "fitness",
  // Resources slugs
  career: "career",
  blog: "blog",
  "how-to-guide": "howToGuide",
  faq: "faq",
  "software-it-services": "softwareIT",
  "custom-software-development": "customSoftwareDevelopment",
  "web-development": "webDevelopment",
  "mobile-app-development": "mobileAppDevelopment",
  "ui-ux-design": "uiuxDesign",
  "ecommerce-solutions": "ecommerceSolutions",
  "cloud-solutions": "cloudSolutions",
  "api-integration": "apiIntegration",
  "maintenance-support": "maintenanceSupport",

  "digital-marketing-services": "digitalMarketingServices",
  seo: "seoServices",
  "social-media-marketing": "socialMediaMarketing",
  "ppc-advertising": "ppcAdvertising",
  "content-marketing": "contentMarketing",
  "email-marketing": "emailMarketing",
  "whatsapp-marketing": "whatsappMarketing",
  "bulk-sms": "bulkSMSMarketing",
  "graphic-design": "graphicDesign",
  "video-marketing": "videoMarketing",
  services: "services",
};
